swagger: '2.0'
info:
  description: API tribu-empresas
  version: 1.0.0
  title: Tribu empresas API
  contact:
    email: fernandmorausky@gmail.com
paths:
  /planetas:
    get:
      tags:
      - Planeta
      summary: Buscar todos los planetas en nuestra DB.
      operationId: buscarPlanetas
      description: |
        Obtener todos los planetas almacenados en nuestra DB
      produces:
      - application/json
      responses:
        200:
          description: Planetas almacenados en nuestra DB
          schema:
            type: object
            properties:
              ok:
                type: boolean
              data:
                type: array
                items:
                  $ref: '#/definitions/planeta'
        400:
          description: Ocurrio un error inesperado
          schema:
            $ref: '#/definitions/error'
  /planeta:
    post:
      tags:
      - Planeta
      summary: Inserta un planeta en nuestra DB.
      operationId: insertaPlaneta
      description: consume API´s de planetas y se inserta a nuestra DB
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: idPlaneta
        description: id de planeta a buscar en las API´s
        schema:
          type: integer
          required:
          - idPlaneta
          properties:
            idPlaneta:
              type: integer
              example: 1
      responses:
        200:
          description: Planeta creado correctamenta
          schema:
            type: object
            properties:
              ok:
                type: boolean
              data:
                type: array
                items:
                  $ref: '#/definitions/planeta'
        400:
          description: Ocurrio un error inesperado
          schema:
            $ref: '#/definitions/error'
  /planeta/{nombre}:
    get:
      tags:
      - Planeta
      summary: Devuelve un planeta 
      operationId: buscarPlaneta
      description: Buscar un planeta de nuestra DB
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        type: string
        name: nombre
        required: true
        description: Nombre planeta
      responses:
        200:
          description: Planeta obetnido
          schema:
            type: object
            properties:
              ok:
                type: boolean
              data:
                $ref: '#/definitions/planeta'
        400:
          description: Planeta no encontrado en nuestra DB
          schema:
            $ref: '#/definitions/error'
definitions:
  planeta:
    type: object
    required:
    - id
    - name
    - manufacturer
    - releaseDate
    properties:
      nombre:
        type: string
        example: Tatooine
      periodo_rotacion:
        type: string
        example: 23
      diametro:
        type: string
        example: 10465
      poblacion:
        type: string
        example: 200000
      clima:
        type: string
        example: arid
      terrenos:
        type: string
        example: desert
      residentes:
        type: array
        items:
          type: object
          properties:
            nombre:
              type: string
              example: Luke Skywalker
            alto:
              type: string
              example: 172
            peso:
              type: string
              example: 77
            color_cabello:
              type: string
              example: blod
            color_ojos:
              type: string
              example: blue
            genero:
              type: string
              example: male
          
  error:
    type: object
    properties:
      ok: 
        type: boolean
        example: false
      err:
        type: object
        properties:
          message:
            type: string
            example: Missing required key 'Key' in params
          code:
            type: string
            example: MissingRequiredParameter
          time:
            type: string
            example: "2020-08-15T19:33:32.822Z"
      
schemes:
 - https
host: n1cy4ppx30.execute-api.us-east-1.amazonaws.com
basePath: /dev